// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Calculate - api that takes two ints
type Calculate struct {
	FirstInt             int32    `protobuf:"varint,1,opt,name=first_int,json=firstInt,proto3" json:"first_int,omitempty"`
	SecondInt            int32    `protobuf:"varint,2,opt,name=second_int,json=secondInt,proto3" json:"second_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculate) Reset()         { *m = Calculate{} }
func (m *Calculate) String() string { return proto.CompactTextString(m) }
func (*Calculate) ProtoMessage()    {}
func (*Calculate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Calculate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculate.Unmarshal(m, b)
}
func (m *Calculate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculate.Marshal(b, m, deterministic)
}
func (m *Calculate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculate.Merge(m, src)
}
func (m *Calculate) XXX_Size() int {
	return xxx_messageInfo_Calculate.Size(m)
}
func (m *Calculate) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculate.DiscardUnknown(m)
}

var xxx_messageInfo_Calculate proto.InternalMessageInfo

func (m *Calculate) GetFirstInt() int32 {
	if m != nil {
		return m.FirstInt
	}
	return 0
}

func (m *Calculate) GetSecondInt() int32 {
	if m != nil {
		return m.SecondInt
	}
	return 0
}

type Number struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Number) Reset()         { *m = Number{} }
func (m *Number) String() string { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()    {}
func (*Number) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *Number) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Number.Unmarshal(m, b)
}
func (m *Number) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Number.Marshal(b, m, deterministic)
}
func (m *Number) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Number.Merge(m, src)
}
func (m *Number) XXX_Size() int {
	return xxx_messageInfo_Number.Size(m)
}
func (m *Number) XXX_DiscardUnknown() {
	xxx_messageInfo_Number.DiscardUnknown(m)
}

var xxx_messageInfo_Number proto.InternalMessageInfo

func (m *Number) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

// CalculateRequest - request object
type CalculateRequest struct {
	Calculate            *Calculate `protobuf:"bytes,1,opt,name=calculate,proto3" json:"calculate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CalculateRequest) Reset()         { *m = CalculateRequest{} }
func (m *CalculateRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateRequest) ProtoMessage()    {}
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *CalculateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateRequest.Unmarshal(m, b)
}
func (m *CalculateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateRequest.Marshal(b, m, deterministic)
}
func (m *CalculateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateRequest.Merge(m, src)
}
func (m *CalculateRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateRequest.Size(m)
}
func (m *CalculateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateRequest proto.InternalMessageInfo

func (m *CalculateRequest) GetCalculate() *Calculate {
	if m != nil {
		return m.Calculate
	}
	return nil
}

// CalculateResponse - response object
type CalculateResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func (m *CalculateResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// stream server Request and Response Objects
type CalculateManyPrimesRequest struct {
	Num                  *Number  `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateManyPrimesRequest) Reset()         { *m = CalculateManyPrimesRequest{} }
func (m *CalculateManyPrimesRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateManyPrimesRequest) ProtoMessage()    {}
func (*CalculateManyPrimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *CalculateManyPrimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateManyPrimesRequest.Unmarshal(m, b)
}
func (m *CalculateManyPrimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateManyPrimesRequest.Marshal(b, m, deterministic)
}
func (m *CalculateManyPrimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateManyPrimesRequest.Merge(m, src)
}
func (m *CalculateManyPrimesRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateManyPrimesRequest.Size(m)
}
func (m *CalculateManyPrimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateManyPrimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateManyPrimesRequest proto.InternalMessageInfo

func (m *CalculateManyPrimesRequest) GetNum() *Number {
	if m != nil {
		return m.Num
	}
	return nil
}

type CalculateManyPrimesResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateManyPrimesResponse) Reset()         { *m = CalculateManyPrimesResponse{} }
func (m *CalculateManyPrimesResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateManyPrimesResponse) ProtoMessage()    {}
func (*CalculateManyPrimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *CalculateManyPrimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateManyPrimesResponse.Unmarshal(m, b)
}
func (m *CalculateManyPrimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateManyPrimesResponse.Marshal(b, m, deterministic)
}
func (m *CalculateManyPrimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateManyPrimesResponse.Merge(m, src)
}
func (m *CalculateManyPrimesResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateManyPrimesResponse.Size(m)
}
func (m *CalculateManyPrimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateManyPrimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateManyPrimesResponse proto.InternalMessageInfo

func (m *CalculateManyPrimesResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// Client Server Stream
type CalculateAverageRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateAverageRequest) Reset()         { *m = CalculateAverageRequest{} }
func (m *CalculateAverageRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateAverageRequest) ProtoMessage()    {}
func (*CalculateAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{6}
}

func (m *CalculateAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateAverageRequest.Unmarshal(m, b)
}
func (m *CalculateAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateAverageRequest.Marshal(b, m, deterministic)
}
func (m *CalculateAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateAverageRequest.Merge(m, src)
}
func (m *CalculateAverageRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateAverageRequest.Size(m)
}
func (m *CalculateAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateAverageRequest proto.InternalMessageInfo

func (m *CalculateAverageRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculateAverageResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateAverageResponse) Reset()         { *m = CalculateAverageResponse{} }
func (m *CalculateAverageResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateAverageResponse) ProtoMessage()    {}
func (*CalculateAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{7}
}

func (m *CalculateAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateAverageResponse.Unmarshal(m, b)
}
func (m *CalculateAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateAverageResponse.Marshal(b, m, deterministic)
}
func (m *CalculateAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateAverageResponse.Merge(m, src)
}
func (m *CalculateAverageResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateAverageResponse.Size(m)
}
func (m *CalculateAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateAverageResponse proto.InternalMessageInfo

func (m *CalculateAverageResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

// Bidirectional Streaming
type CalculateMaxRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateMaxRequest) Reset()         { *m = CalculateMaxRequest{} }
func (m *CalculateMaxRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateMaxRequest) ProtoMessage()    {}
func (*CalculateMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{8}
}

func (m *CalculateMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateMaxRequest.Unmarshal(m, b)
}
func (m *CalculateMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateMaxRequest.Marshal(b, m, deterministic)
}
func (m *CalculateMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateMaxRequest.Merge(m, src)
}
func (m *CalculateMaxRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateMaxRequest.Size(m)
}
func (m *CalculateMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateMaxRequest proto.InternalMessageInfo

func (m *CalculateMaxRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculateMaxResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateMaxResponse) Reset()         { *m = CalculateMaxResponse{} }
func (m *CalculateMaxResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateMaxResponse) ProtoMessage()    {}
func (*CalculateMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{9}
}

func (m *CalculateMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateMaxResponse.Unmarshal(m, b)
}
func (m *CalculateMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateMaxResponse.Marshal(b, m, deterministic)
}
func (m *CalculateMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateMaxResponse.Merge(m, src)
}
func (m *CalculateMaxResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateMaxResponse.Size(m)
}
func (m *CalculateMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateMaxResponse proto.InternalMessageInfo

func (m *CalculateMaxResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

// unnary request for square root
type SquareRootRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootRequest) Reset()         { *m = SquareRootRequest{} }
func (m *SquareRootRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootRequest) ProtoMessage()    {}
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{10}
}

func (m *SquareRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootRequest.Unmarshal(m, b)
}
func (m *SquareRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootRequest.Marshal(b, m, deterministic)
}
func (m *SquareRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootRequest.Merge(m, src)
}
func (m *SquareRootRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootRequest.Size(m)
}
func (m *SquareRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootRequest proto.InternalMessageInfo

func (m *SquareRootRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SquareRootResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootResponse) Reset()         { *m = SquareRootResponse{} }
func (m *SquareRootResponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootResponse) ProtoMessage()    {}
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{11}
}

func (m *SquareRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootResponse.Unmarshal(m, b)
}
func (m *SquareRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootResponse.Marshal(b, m, deterministic)
}
func (m *SquareRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootResponse.Merge(m, src)
}
func (m *SquareRootResponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootResponse.Size(m)
}
func (m *SquareRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootResponse proto.InternalMessageInfo

func (m *SquareRootResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculate)(nil), "calculator.Calculate")
	proto.RegisterType((*Number)(nil), "calculator.Number")
	proto.RegisterType((*CalculateRequest)(nil), "calculator.CalculateRequest")
	proto.RegisterType((*CalculateResponse)(nil), "calculator.CalculateResponse")
	proto.RegisterType((*CalculateManyPrimesRequest)(nil), "calculator.CalculateManyPrimesRequest")
	proto.RegisterType((*CalculateManyPrimesResponse)(nil), "calculator.CalculateManyPrimesResponse")
	proto.RegisterType((*CalculateAverageRequest)(nil), "calculator.CalculateAverageRequest")
	proto.RegisterType((*CalculateAverageResponse)(nil), "calculator.CalculateAverageResponse")
	proto.RegisterType((*CalculateMaxRequest)(nil), "calculator.CalculateMaxRequest")
	proto.RegisterType((*CalculateMaxResponse)(nil), "calculator.CalculateMaxResponse")
	proto.RegisterType((*SquareRootRequest)(nil), "calculator.SquareRootRequest")
	proto.RegisterType((*SquareRootResponse)(nil), "calculator.SquareRootResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x8f, 0xd2, 0x40,
	0x10, 0xb6, 0x36, 0x34, 0x76, 0x20, 0x2a, 0xa3, 0x22, 0x29, 0xa2, 0xb8, 0x12, 0x25, 0x41, 0x11,
	0x21, 0xfe, 0x00, 0xf1, 0x81, 0xf0, 0x50, 0x63, 0xca, 0x83, 0x89, 0x2f, 0x97, 0xd2, 0x5b, 0x2e,
	0x4d, 0xe8, 0x16, 0xb6, 0x5b, 0xc2, 0xfd, 0xcf, 0xfb, 0x41, 0x97, 0x6b, 0xbb, 0xed, 0x12, 0xda,
	0xeb, 0x5b, 0x67, 0xe6, 0x9b, 0xef, 0xfb, 0x76, 0x66, 0x52, 0x18, 0x79, 0xee, 0xce, 0x8b, 0x77,
	0xae, 0x08, 0xf9, 0xf7, 0xe2, 0x73, 0xbf, 0x51, 0x82, 0xc9, 0x9e, 0x87, 0x22, 0x44, 0x28, 0x32,
	0x64, 0x09, 0xe6, 0xef, 0x2c, 0xa2, 0xd8, 0x03, 0x73, 0xeb, 0xf3, 0x48, 0x5c, 0xf9, 0x4c, 0x74,
	0xb5, 0x81, 0x36, 0x6a, 0x38, 0xcf, 0x92, 0xc4, 0x8a, 0x09, 0xec, 0x03, 0x44, 0xd4, 0x0b, 0xd9,
	0x75, 0x52, 0x7d, 0x9a, 0x54, 0xcd, 0x34, 0xb3, 0x62, 0x82, 0x8c, 0xc1, 0xf8, 0x13, 0x07, 0x1b,
	0xca, 0xf1, 0x23, 0xb4, 0x52, 0x16, 0x96, 0xc4, 0x19, 0x51, 0x33, 0xc9, 0xa5, 0x10, 0xb2, 0x84,
	0x97, 0xb9, 0xaa, 0x43, 0x0f, 0x31, 0x8d, 0x04, 0xce, 0xc1, 0x94, 0xbe, 0x68, 0xd2, 0xd3, 0x9c,
	0xbd, 0x99, 0x28, 0xde, 0x8b, 0x86, 0x02, 0x47, 0xc6, 0xd0, 0x56, 0x88, 0xa2, 0x7d, 0xc8, 0x22,
	0x8a, 0x1d, 0x30, 0x38, 0x8d, 0xe2, 0x9d, 0x7c, 0x43, 0x16, 0x91, 0x05, 0x58, 0x39, 0xd8, 0x76,
	0xd9, 0xed, 0x5f, 0xee, 0x07, 0x34, 0x92, 0xfa, 0x43, 0xd0, 0x59, 0x1c, 0x64, 0xca, 0xa8, 0x2a,
	0xa7, 0xa6, 0x9d, 0x87, 0x32, 0xf9, 0x09, 0xbd, 0x52, 0x8e, 0x1a, 0xe9, 0x1f, 0xf0, 0x36, 0x6f,
	0xfb, 0x75, 0xa4, 0xdc, 0xbd, 0xc9, 0xdf, 0xdd, 0x01, 0x43, 0x19, 0x94, 0xee, 0x64, 0x11, 0x99,
	0x41, 0xf7, 0xb2, 0xa5, 0x54, 0x46, 0xcf, 0x65, 0xbe, 0xc1, 0x2b, 0xc5, 0xdd, 0xa9, 0x4e, 0x62,
	0x02, 0xaf, 0xcf, 0xe1, 0x35, 0xf4, 0x63, 0x68, 0xaf, 0x0f, 0xb1, 0xcb, 0xa9, 0x13, 0x86, 0xa2,
	0x9c, 0xbc, 0x91, 0x93, 0x7f, 0x05, 0x54, 0xc1, 0xa5, 0xd4, 0x9a, 0xa4, 0x9e, 0xdd, 0xe9, 0xca,
	0x49, 0xac, 0x29, 0x3f, 0xfa, 0x1e, 0x45, 0x1b, 0x5a, 0x45, 0x2e, 0x0e, 0xf0, 0x5d, 0xf9, 0x3d,
	0xa4, 0x46, 0xac, 0x7e, 0x45, 0x35, 0x55, 0x26, 0x4f, 0x70, 0x0b, 0x2f, 0xf2, 0x74, 0xba, 0x37,
	0xfc, 0x5c, 0xda, 0x73, 0x71, 0x1c, 0xd6, 0x97, 0x5a, 0x9c, 0x54, 0x99, 0x6a, 0xe8, 0x2a, 0x4f,
	0xc9, 0x36, 0x87, 0x9f, 0x4a, 0x09, 0xce, 0x4f, 0xc1, 0x1a, 0x3e, 0x0e, 0x92, 0x12, 0x23, 0x0d,
	0xff, 0x29, 0x93, 0xb1, 0xdd, 0x13, 0x7e, 0xa8, 0xf0, 0x27, 0x4f, 0xc0, 0x1a, 0x54, 0x03, 0x0a,
	0xda, 0xa9, 0x86, 0x36, 0x40, 0xb1, 0x35, 0x3c, 0x1b, 0xe9, 0xc5, 0xea, 0xad, 0xf7, 0x55, 0x65,
	0x49, 0xb9, 0x78, 0xfe, 0xbf, 0xa5, 0xfe, 0x8b, 0x36, 0x46, 0xf2, 0x07, 0x9a, 0xdf, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0x7b, 0x8f, 0x11, 0xad, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculateServiceClient is the client API for CalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateServiceClient interface {
	// unary API call
	CalculateSum(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	// server streaming
	CalculatePrimes(ctx context.Context, in *CalculateManyPrimesRequest, opts ...grpc.CallOption) (CalculateService_CalculatePrimesClient, error)
	// client streaming
	CalculateAverage(ctx context.Context, opts ...grpc.CallOption) (CalculateService_CalculateAverageClient, error)
	// bidirectional streaming
	CalculateMax(ctx context.Context, opts ...grpc.CallOption) (CalculateService_CalculateMaxClient, error)
	// unary api call
	// rpc will throw an exception if the number is negative
	// the error thrown out is of type INVALID_ARGUEMENT
	SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
}

type calculateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculateServiceClient(cc *grpc.ClientConn) CalculateServiceClient {
	return &calculateServiceClient{cc}
}

func (c *calculateServiceClient) CalculateSum(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/CalculateSum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) CalculatePrimes(ctx context.Context, in *CalculateManyPrimesRequest, opts ...grpc.CallOption) (CalculateService_CalculatePrimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[0], "/calculator.CalculateService/CalculatePrimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServiceCalculatePrimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculateService_CalculatePrimesClient interface {
	Recv() (*CalculateManyPrimesResponse, error)
	grpc.ClientStream
}

type calculateServiceCalculatePrimesClient struct {
	grpc.ClientStream
}

func (x *calculateServiceCalculatePrimesClient) Recv() (*CalculateManyPrimesResponse, error) {
	m := new(CalculateManyPrimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateServiceClient) CalculateAverage(ctx context.Context, opts ...grpc.CallOption) (CalculateService_CalculateAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[1], "/calculator.CalculateService/CalculateAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServiceCalculateAverageClient{stream}
	return x, nil
}

type CalculateService_CalculateAverageClient interface {
	Send(*CalculateAverageRequest) error
	CloseAndRecv() (*CalculateAverageResponse, error)
	grpc.ClientStream
}

type calculateServiceCalculateAverageClient struct {
	grpc.ClientStream
}

func (x *calculateServiceCalculateAverageClient) Send(m *CalculateAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateServiceCalculateAverageClient) CloseAndRecv() (*CalculateAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CalculateAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateServiceClient) CalculateMax(ctx context.Context, opts ...grpc.CallOption) (CalculateService_CalculateMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[2], "/calculator.CalculateService/CalculateMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServiceCalculateMaxClient{stream}
	return x, nil
}

type CalculateService_CalculateMaxClient interface {
	Send(*CalculateMaxRequest) error
	Recv() (*CalculateMaxResponse, error)
	grpc.ClientStream
}

type calculateServiceCalculateMaxClient struct {
	grpc.ClientStream
}

func (x *calculateServiceCalculateMaxClient) Send(m *CalculateMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateServiceCalculateMaxClient) Recv() (*CalculateMaxResponse, error) {
	m := new(CalculateMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateServiceClient) SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/SquareRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculateServiceServer is the server API for CalculateService service.
type CalculateServiceServer interface {
	// unary API call
	CalculateSum(context.Context, *CalculateRequest) (*CalculateResponse, error)
	// server streaming
	CalculatePrimes(*CalculateManyPrimesRequest, CalculateService_CalculatePrimesServer) error
	// client streaming
	CalculateAverage(CalculateService_CalculateAverageServer) error
	// bidirectional streaming
	CalculateMax(CalculateService_CalculateMaxServer) error
	// unary api call
	// rpc will throw an exception if the number is negative
	// the error thrown out is of type INVALID_ARGUEMENT
	SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
}

// UnimplementedCalculateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServiceServer struct {
}

func (*UnimplementedCalculateServiceServer) CalculateSum(ctx context.Context, req *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSum not implemented")
}
func (*UnimplementedCalculateServiceServer) CalculatePrimes(req *CalculateManyPrimesRequest, srv CalculateService_CalculatePrimesServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculatePrimes not implemented")
}
func (*UnimplementedCalculateServiceServer) CalculateAverage(srv CalculateService_CalculateAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateAverage not implemented")
}
func (*UnimplementedCalculateServiceServer) CalculateMax(srv CalculateService_CalculateMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateMax not implemented")
}
func (*UnimplementedCalculateServiceServer) SquareRoot(ctx context.Context, req *SquareRootRequest) (*SquareRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}

func RegisterCalculateServiceServer(s *grpc.Server, srv CalculateServiceServer) {
	s.RegisterService(&_CalculateService_serviceDesc, srv)
}

func _CalculateService_CalculateSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).CalculateSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/CalculateSum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).CalculateSum(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_CalculatePrimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculateManyPrimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServiceServer).CalculatePrimes(m, &calculateServiceCalculatePrimesServer{stream})
}

type CalculateService_CalculatePrimesServer interface {
	Send(*CalculateManyPrimesResponse) error
	grpc.ServerStream
}

type calculateServiceCalculatePrimesServer struct {
	grpc.ServerStream
}

func (x *calculateServiceCalculatePrimesServer) Send(m *CalculateManyPrimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculateService_CalculateAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServiceServer).CalculateAverage(&calculateServiceCalculateAverageServer{stream})
}

type CalculateService_CalculateAverageServer interface {
	SendAndClose(*CalculateAverageResponse) error
	Recv() (*CalculateAverageRequest, error)
	grpc.ServerStream
}

type calculateServiceCalculateAverageServer struct {
	grpc.ServerStream
}

func (x *calculateServiceCalculateAverageServer) SendAndClose(m *CalculateAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateServiceCalculateAverageServer) Recv() (*CalculateAverageRequest, error) {
	m := new(CalculateAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculateService_CalculateMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServiceServer).CalculateMax(&calculateServiceCalculateMaxServer{stream})
}

type CalculateService_CalculateMaxServer interface {
	Send(*CalculateMaxResponse) error
	Recv() (*CalculateMaxRequest, error)
	grpc.ServerStream
}

type calculateServiceCalculateMaxServer struct {
	grpc.ServerStream
}

func (x *calculateServiceCalculateMaxServer) Send(m *CalculateMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateServiceCalculateMaxServer) Recv() (*CalculateMaxRequest, error) {
	m := new(CalculateMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculateService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/SquareRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).SquareRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculateService",
	HandlerType: (*CalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSum",
			Handler:    _CalculateService_CalculateSum_Handler,
		},
		{
			MethodName: "SquareRoot",
			Handler:    _CalculateService_SquareRoot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculatePrimes",
			Handler:       _CalculateService_CalculatePrimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CalculateAverage",
			Handler:       _CalculateService_CalculateAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CalculateMax",
			Handler:       _CalculateService_CalculateMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
